#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[1;36m'
NC='\033[0m'

if [ -z $DEV_ENV ]; then
  script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
else
  script_dir=$DEV_ENV
fi

if [ -z $HOSTNAME ]; then
  HOSTNAME=$(uname -n)
fi

dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo -e "${RED}[DRY RUN]:${NC} $@"
  else
    echo -e "$@"
  fi
}

execute() {
  log "${GREEN}execute $@${NC}"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

copy_dir() {
  from=$1
  to=$2

  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2
  name=$3
  if [ -z $3 ]; then
    name=$(basename $from)
  fi

  execute rm $to/$name
  execute cp $from $to/$name
}

echo -e "---------------[ ${CYAN}dev-env${NC} ]---------------"
echo -e "${CYAN}[OS]: ${NC}Running for ${os}"

echo -e "${CYAN}[GROUP]:${NC} Universal"
execute mkdir $HOME/personal
execute mkdir $HOME/school
execute mkdir $HOME/work
execute mkdir $HOME/aur

execute mkdir $HOME/.local/bin
copy_file scripts/tmux-sessionizer $HOME/.local/bin/
copy_file scripts/tmux-mkdir $HOME/.local/bin/
copy_file scripts/tmux-devenv $HOME/.local/bin/
copy_file scripts/optvideo4web $HOME/.local/bin/
copy_file scripts/time-report $HOME/.local/bin/

copy_dir dotfiles/.config $HOME/.config
copy_file dotfiles/.config/hypr/host/$HOSTNAME.conf $HOME/.config/hypr hostname.conf

copy_file dotfiles/.zshrc $HOME
copy_file dotfiles/.zsh_profile $HOME
copy_file dotfiles/.gitconfig $HOME

execute hyprctl reload
