#!/usr/bin/env bash

if [ -z "$@" ]; then
  echo -en "Shutdown\0icon\x1fsystem-shutdown-symbolic\n"
  echo -en "Reboot\0icon\x1fsystem-reboot-symbolic\x1fmeta\x1fRestart\n"
else
  case "$@" in
    *Shutdown*)
      hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'
      ;;
    *Reboot*)
      hyprshutdown -t 'Rebooting...' --post-cmd 'reboot'
      ;;
  esac
fi
