#!/usr/bin/env bash

usage() {
  local prog=${0##*/}
  cat << EOF
Usage: $prog [options]

Mount Jarbo remote resources.

Options
  -h                Print usage message
  -u                Unmount a resource
EOF
}

fatal() {
  echo "$@" >&2
  exit 1
}

mount_targets=$(
  {
    awk -v home=$HOME '
      !/^[[:space:]]*#/ && NF >= 2 {
        target = $2
        sub(/__HOME__/, home, target)
        name = target
        sub(/^.*\//, "", name)
        print "CIFS\t" name "\t" target
      }
    ' "$HOME/personal/dev-env/system/etc/jarbo.fstab"

    find "$HOME/work" \
      -mindepth 1 \
      -maxdepth 1 \
      -type d \
      -exec test -e "{}/mntconfig" \; \
      -printf 'SSHFS\t%f\t%p/mnt\n'
  } | sort -u
)

mounted=$(
  awk -F '\t' '
    NR==FNR { mounted_paths[$0]; next }
    $3 in mounted_paths
  ' <(findmnt -o TARGET -D -n) <(printf '%s\n' "$mount_targets")
)

available=$(
  awk -F '\t' '
    NR==FNR { mounted_paths[$0]; next }
    !($3 in mounted_paths)
  ' <(findmnt -o TARGET -D -n) <(printf '%s\n' "$mount_targets")
)

select_mount() {
  mount_option=$(printf '%s\n' "$available" | fzf --delimiter=$'\t' --with-nth=2)
  if [[ -z "$mount_option" ]]; then
    echo "No mount selected"
    exit 0
  fi

  IFS=$'\t' read -r type name target <<< "$mount_option"

  case "$type" in
    CIFS) 
      mkdir -p "$target" 2> /dev/null
      mount "$target"
      ;;
    SSHFS) 
      client_dir=$(dirname "$target")
      read -r host user port path < "$client_dir/mntconfig"
      mkdir $target 2> /dev/null
      sshfs $user@$host:$path $target -p $port -o IdentityFile=~/work/general/sgkey
      ;;
    *) echo "Unknown mount type $type" >&2; exit 1;;
  esac

  echo "Mounted $name"
}

select_unmount() {
  mount_option=$(printf '%s\n' "$mounted" | fzf --delimiter=$'\t' --with-nth=2)
  if [[ -z "$mount_option" ]]; then
    echo "No mount selected"
    exit 0
  fi

  IFS=$'\t' read -r type name target <<< "$mount_option"

  case "$target" in
    $HOME/mounts*) umount $target;;
    $HOME/work*) fusermount3 -u $target;;
  esac

  echo "Unmounted $name"
}

main() {
  local opt OPTIND OPTARG
  while getopts 'hu' opt; do
    case "$opt" in
      h) usage; exit 0;;
      u) select_unmount; exit 0;;
      *) usage; exit 1;;
    esac
  done

  if [[ ! -f "$HOME/.smbcredentials" ]]; then
    fatal "Missing credentials file, create it at ~/.smbcredentials"
  elif [[ $(stat -c '%a' "$HOME/.smbcredentials" 2> /dev/null) != "600" ]]; then
    fatal "Credentials file permissions are not 600"
  fi

  select_mount
}

main "$@"
