#!/usr/bin/env bash

. ~/scriptlib/progress
. ~/scriptlib/spinner

usage() {
  local prog=${0##*/}
  cat << EOF
Usage: $prog [options] <cmd>

Optimize video files for web.

Options
  -h          Print usage message
  -f <file>   File to convert
  -d <ext>    Convert files with the given extension in the current directory
  -s <size>   Resize the output video(s)
  -v          Enable verbose output
EOF
}

fatal() {
  echo "$@" >&2
  exit 1
}

MULTI=false
FILTER=""
SCALE=""
VERBOSE=false

get_size() {
  s=$1
  if [[ "$s" =~ ^[0-9]+x[0-9]+$ ]]; then
    SCALE=$s
  else
    fatal "Invalid scale value: $s. Should be in format 1280x720"
  fi
}

optimize_file() {
  source=$1
  dest=$2

  cmd="ffmpeg -y -i $source -c:v libx264 -b:v 3M -strict -2 -movflags faststart"
  if [ -n "$SCALE" ]; then
    cmd="$cmd -s $SCALE"
  fi
  if $VERBOSE; then
    cmd="$cmd $dest"
  else
    cmd="($cmd -hide_banner -loglevel quiet $dest) &> /dev/null & disown"
  fi

  echo "Optimizing $source..."
  $("$cmd")
  echo "    Optimized $source"
  oldbytes=`stat -c%s "$source"`
  oldsize=`awk -v n=$oldbytes 'BEGIN {printf "%.2f\n", (n/1000000)}'`
  newbytes=`stat -c%s "$dest"`
  newsize=`awk -v n=$newbytes 'BEGIN {printf "%.2f\n", (n/1000000)}'`
  echo "    Original size: $oldsize MB"
  echo "    Optimized size: $newsize MB"
}

main() {
  local opt OPTIND OPTARG
  while getopts 'f:d:s:hv' opt; do
    case "$opt" in
      h) usage; return 0;;
      f) MULTI=false; FILTER=${OPTARG};;
      d) MULTI=true; FILTER=${OPTARG};;
      s) get_size ${OPTARG};;
      v) VERBOSE=true;;
      *) usage; return 1;;
    esac
  done

  mkdir ./ov4w &> /dev/null

  if $MULTI; then
    progress-init
    count=`find . -maxdepth 1 -name "*.$FILTER" | wc -l | tr -d ' '`
    if (($count == 0)); then
      fatal "No matching files found"
    fi
    current=0
    progress-bar "$current" "$count" 

    for filename in *."$FILTER"; do
      spinner optimize_file "./$filename" "./ov4w/$filename"
      current=$(($current + 1))
      progress-bar "$current" "$count"
    done
  else
    spinner optimize_file "./$FILTER" "./ov4w/$FILTER"
  fi
}

main "$@"
