#!/usr/bin/env bash

usage() {
  echo "Usage: jarbo-mount"
  echo ""
  echo "By default, mounts the Active Clients share to ~/mounts/active-clients"
  echo ""
  echo "  Options:"
  echo "    -s <share>          Specify a specific share on the server"
  echo "    -m <mount point>    Specify a custom name for the mount point"
  echo "    -g                  Mount a client SFTP"
  echo "    -u                  Unmount a client SFTP"
}

fatal() {
  echo '[FATAL]' "$@" >&2
  exit 1
}

spinner() {
  local info="$1"
  local pid=$!
  local delay=0.25
  local spinstr='|/-\'
  while kill -0 $pid 2> /dev/null; do
    local temp=${spinstr#?}
    printf " [%c] $info" "$spinstr"
    local spinstr=$temp${spinstr%"$temp"}
    sleep $delay
    printf "\e[0G"
  done
  printf "    \b\b\b\b"
}

multi=false
filter=""
scale=""
verbose=false

get_size() {
  s=$1
  if [[ "$s" =~ ^[0-9]+x[0-9]+$ ]]; then
    scale=$s
  else
    fatal "invalid scale value: $s. should be in format 1280x720"
  fi
}

optimize_file() {
  source=$1
  dest=$2
  curr=$3
  total=$4
  if [ $verbose == true ]; then
    if [ -n "$scale" ]; then
      ffmpeg -y -i "$source" -c:v libx264 -b:v 3M -s "$scale" -strict -2 -movflags faststart "$dest"
    else
      ffmpeg -y -i "$source" -c:v libx264 -b:v 3M -strict -2 -movflags faststart "$dest"
    fi
  else
    if [ -n "$scale" ]; then
      (ffmpeg -hide_banner -loglevel quiet -y -i "$source" -c:v libx264 -b:v 3M -s "$scale" -strict -2 -movflags faststart "$dest") &> /dev/null & disown
    else
      (ffmpeg -hide_banner -loglevel quiet -y -i "$source" -c:v libx264 -b:v 3M -strict -2 -movflags faststart "$dest") &> /dev/null & disown
    fi
    if [ -z "$curr" ]; then
      curr=1
    fi
    if [ -z "$total" ]; then
      total=1
    fi
    spinner "Optimizing $source... ($curr/$total)"
    echo "    Optimized $source ($curr/$total)"
    oldbytes=`stat -c%s "$source"`
    oldsize=`awk -v n=$oldbytes 'BEGIN {printf "%.2f\n", (n/1000000)}'`
    newbytes=`stat -c%s "$dest"`
    newsize=`awk -v n=$newbytes 'BEGIN {printf "%.2f\n", (n/1000000)}'`
    echo "    Original size: $oldsize MB"
    echo "    Optimized size: $newsize MB"
  fi
}

while getopts 'f:d:s:hv' o; do
  case "${o}" in
    h) usage; exit 0;;
    f) multi=false; filter=${OPTARG};;
    d) multi=true; filter=${OPTARG};;
    s) get_size ${OPTARG};;
    v) verbose=true;;
    *) fatal "invalid argument: $opt";;
  esac
done

mkdir ./ov4w &> /dev/null

if [ $multi == true ]; then
  count=`find . -maxdepth 1 -name "*.$filter" | wc -l | tr -d ' '`
  current=1
  for filename in *."$filter"; do
    optimize_file "./$filename" "./ov4w/$filename" "$current" "$count"
  done
else
  optimize_file "./$filter" "./ov4w/$filter"
fi
