#!/usr/bin/env bash

sudo pacman -S --needed ripgrep ffmpeg composer nvm pvgo fzf udiskie unzip npm interception-tools brightnessctl ttf-sourcecodepro-nerd wl-clipboard cups ghostscript less

# node / npm
cd $HOME/Downloads
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
nvm install 22
