#!/usr/bin/env bash

sudo pacman -S --needed base-devel ripgrep ffmpeg composer nvm go rust fzf sshfs udiskie unzip usbutils interception-tools brightnessctl ttf-sourcecodepro-nerd wl-clipboard cups ghostscript less xdg-desktop-portal-gtk github-cli slurp grim wine wine-mono libwebp libwebp-utils jq openbsd-netcat

source ~/.nvm/nvm.sh

nvm install 24
nvm use 24
