#!/usr/bin/env bash

sudo pacman -S --needed base-devel ripgrep ffmpeg composer nvm go fzf udiskie unzip usbutils interception-tools brightnessctl ttf-sourcecodepro-nerd wl-clipboard cups ghostscript less xdg-desktop-portal-gtk github-cli

source ~/.nvm/nvm.sh

nvm install 24
nvm use 24
