#!/usr/bin/env bash

source ~/.nvm/nvm.sh

LSPDIR=$HOME/.local/lsp

mkdir $LSPDIR

sudo rm -rf $LSPDIR/*

sudo pacman -S --needed \
  lua-language-server \
	marksman \
	bash-language-server \
	yaml-language-server \
	typescript \
	typescript-language-server \
	gopls \
	vscode-html-languageserver \
	vscode-css-languageserver \
	vscode-json-languageserver \
  pyright

npm i -g \
  sql-language-server \
  intelephense
