#!/usr/bin/env bash

source ~/.nvm/nvm.sh

LSPDIR=$HOME/.local/lsp

mkdir $LSPDIR

sudo pacman -S --needed lua-language-server marksman

# html, cssls, jsonls
npm i -g vscode-langservers-extracted

# css-variables
npm i -g css-variables-language-server

# ts_ls
npm i -g typescript typescript-language-server

# phpactor
cd $LSPDIR
git clone https://github.com/phpactor/phpactor.git $LSPDIR/phpactor
cd phpactor
composer install
sudo ln -s $LSPDIR/phpactor/bin/phpactor /usr/local/bin/phpactor

# sqlls
npm i -g sql-language-server

# bashls
npm i -g bash-language-server

# gopls
go install golang.org/x/tools/gopls@latest

# yamlls
npm i -g yaml-language-server
